### PR TITLE
Update common files in release-1.3

### PR DESCRIPTION
**Pull request by rlenglet**
Manually backports https://github.com/istio/cni/pull/163, https://github.com/istio/cni/pull/164, https://github.com/istio/cni/pull/170.

Update common files, define new lint targets, etc. to re-enable builds on `release-1.3`.
Disable Golang linters that are not yet enabled in `master`: `funlen`, `bodyclose`.

Fixes: https://github.com/istio/test-infra/pull/1790

### CODE REVIEW

**Comment by rlenglet** [comment]
`lintmodern_cni_release-1.3` passed.

**Comment by rlenglet** [comment]
@geeknoid PTAL

**Comment by geeknoid** [comment]
The problem is versioning I think.

- Update the common files in both master and in release-1.3
- Update build jobs in test-infra to use the same container version.

**Comment by rlenglet** [comment]
This is not just a problem of versioning. Container-based build was enabled in https://github.com/istio/test-infra/pull/1790 without first backporting the changes to make that work in the `release-1.3` branch. This is what this PR does.

**Review by geeknoid — APPROVED** [review]

**Comment by rlenglet** [comment]
@brian-avery @sdake I need your approval for this PR which fixes all builds in `istio/cni:release-1.3`.

**Review by brian-avery — APPROVED** [review]

**Pull request merged**
