### PR TITLE
Update common files.

### PR DESCRIPTION
**Pull request by geeknoid**

### CODE REVIEW

**Comment by geeknoid** [comment]
@rlenglet Are the CI failures flakes? I can't retry since I don't have the right permissions on this repo...

**Comment by rlenglet** [comment]
Those test failures are due to the CNI test images still using Go 1.10, which started breaking due to istio/istio now requiring 1.12 to build istioctl. This will be fixed by moving the e2e tests to Prow. @howardjohn merged a PR into master to do that, which we'll backport soon.
I'll force-merge this PR.

**Comment by rlenglet** [comment]
I forgot to add the cherrypick label...

**Pull request merged**
