### PR TITLE
add kubevirt interfaces to istio CNI

### PR DESCRIPTION
**Pull request by SchSeba**
Related to https://github.com/istio/istio/pull/11321 and https://github.com/istio/istio/pull/10378

add kubevirt interfaces annotation to istio cni

### CODE REVIEW

**Comment by tiswanso** [comment]
#88 is needed in the istio-cni release-1.1 branch for the tests on this PR to run.  Will try to get that merged in and then will have you rebase

**Comment by SchSeba** [comment]
Hi @tiswanso thanks for the comment I saw https://github.com/istio/cni/pull/88 was mege to master there is any intention to merge it also for release 1.1?

**Comment by tiswanso** [comment]
@SchSeba  could you just cherry-pick this onto master and we'll get it in there and merge it into 1.1?

**Comment by john-a-joyce** [comment]
Closing this as on CNI we are committing only to master and pulling any needed commits form Master on to release 1.1.   Since there is no direct linkage between istio 1.1 and CNI 1.1 now anyway.  99% of the time people will use CNI master unless specifically pegging a version.

**Pull request closed without merging**
