### PR TITLE
[release-1.4] Update to common-files to implement docker.push (#207)

### PR DESCRIPTION
**Pull request by sdake**
Manual cherry-pick of aece88de0ff43ff319434a52d7d70dbc4f328a56.

Conflicts:
	common/.commonfiles.sha
	common/Makefile.common.mk

### CODE REVIEW

**Comment by ericvn** [comment]
There are a few problems with this PR:

1) The common-files SHA is a _master_branch SHA.
2) The UPDATE branch in the Makefile is _master_ which will force a new _update-common_ to pull from master.

Based on earlier discussion, I think we want to cherry-pick https://github.com/istio/common-files/pull/111 pack to release-1.4 and then we'll do the _make update-common_ to get the changes. Please correct me if I misunderstood @howardjohn .

**Comment by howardjohn** [comment]
Yes that is correct, we should be using 1.4 specific common files.

Do we really need this in 1.4 anyways?

**Comment by sdake** [comment]
I don't mind following a different process for common-files then the rest of Istio even though it is inconsistent.  @ericvn what you propose makes more sense.  I'm not sure we have done a good job of backporting common-files fixes to the 1.4 branch.

We don't need docker push, but **we do need other parts of this common-files PR** (the stuff that sets the TARGET_OUT dir, as well as the latest images) so that the architecture is set correctly.

@geeknoid may have some thoughts on the rollout of common-files to the master branches.  He has undertaken this for master.  I am unclear on his recommended approach for 1.4.

Cheers
-steve

**Comment by sdake** [comment]
spoke with @geeknoid in general about our 1.4 rollout plans are for the repos.  He will sort out cni, so closing this PR.

Cheers
-steve

**Pull request closed without merging**
