### PR TITLE
Fix ShellCheck issues

### PR DESCRIPTION
**Pull request by rlenglet**
Re-enable the `shellcheck` CircleCI job. Fix ShellCheck issues.

### CODE REVIEW

**Comment by rlenglet** [comment]
@tiswanso 

> Need to remove istio-iptables.sh from this changeset. It is not an exact duplicate of istio/istio's due to locking issues when run via CNI. Additionally, there's an existing PR for the IPv6 additions including IPv6 CI job.

Thanks for your review. I'm aware that `istio-iptables.sh` is forked from istio/istio. I'm still working on tihis. This PR is still WIP and had the `do-not-merge/work-in-progress` label. I had to create a PR to test the new CircleCI job. I added `[WIP]` to this PR's title to clarify. Sorry for the noise.

**Comment by tiswanso** [comment]
> @tiswanso
> 
> > Need to remove istio-iptables.sh from this changeset. It is not an exact duplicate of istio/istio's due to locking issues when run via CNI. Additionally, there's an existing PR for the IPv6 additions including IPv6 CI job.
> 
> Thanks for your review. I'm aware that `istio-iptables.sh` is forked from istio/istio. I'm still working on tihis. This PR is still WIP and had the `do-not-merge/work-in-progress` label. I had to create a PR to test the new CircleCI job. I added `[WIP]` to this PR's title to clarify. Sorry for the noise.

Thanks for the clarification that its WIP.  Could you clarify the intent of what you're doing in istio-iptables.sh?  The subject indicates you're sync'ing istio-iptables.sh and I disagree with doing that in this PR.

**Comment by rlenglet** [comment]
@tiswanso
> The subject indicates you're sync'ing istio-iptables.sh and I disagree with doing that in this PR.

OK. I've spun this out into https://github.com/istio/cni/pull/113. That will have to get merged first since fixing ShellCheck depends on updating `istio-iptables.sh` first.

**Comment by rlenglet** [comment]
This is ready for review. Thanks!

**Pull request merged**
